version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: docker
    directory: '/server'
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: '/client'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/client'
    schedule:
      interval: daily