version: "3.9"

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: devword
      POSTGRES_USER: dev
      POSTGRES_DB: app
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
  server:
    image: ghcr.io/wesleyklop/volgendeverjaardag.nl-server:latest
    build:
      context: server
      target: dev
    expose:
      - 8080
    environment:
      DATABASE_URL: postgres://dev:devword@database:5432/app?schema=public
    depends_on:
      - database
    volumes:
      - ./server:/usr/src/app
  client:
    image: ghcr.io/wesleyklop/volgendeverjaardag.nl-client:latest
    build:
      context: client
      target: dev
    ports:
      - 8081:8080
    environment:
      API_HOST: server
    restart: on-failure
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app

volumes:
  db-data:
