version: "3.9"

services:
  server:
    image: ghcr.io/wesleyklop/birthday-server
    build:
      context: server
      target: builder
    ports:
      - 8080
    environment:
      DATABASE_URL: postgres://dev:devword@database:5432/app?schema=public
    depends_on:
      - database
    volumes:
      - ./server:/usr/src/app
  database:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: devword
      POSTGRES_USER: dev
      POSTGRES_DB: app
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
