name="volgendeverjaardag"
pages_build_output_dir="./dist"
compatibility_date = "2025-02-09"

[[d1_databases]]
binding = "DB"
preview_database_id = "DB"
database_name = "volgendeverjaardag_preview"
database_id = "01946e4a-d8f0-4cdc-9be4-0002886f6f07"
migrations_dir = "./migrations"

[[env.production.d1_databases]]
binding = "DB"
database_name = "volgendeverjaardag"
database_id = "ab4e6079-33f4-4614-be5c-574b49b7123f"
migrations_dir = "./migrations"

