apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/client-deployment.yaml
  - resources/client-service.yaml
  - resources/server-deployment.yaml
  - resources/server-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: volgendeverjaardag
    includeSelectors: true

images:
  - name: ghcr.io/wesleyklop/volgendeverjaardag.nl-client
    newTag: 1.1.2
  - name: ghcr.io/wesleyklop/volgendeverjaardag.nl-server
    newTag: 1.1.2
