apiVersion: v1
kind: Service
metadata:
  name: volgendeverjaardag-client
spec:
  selector:
    app.kubernetes.io/name: volgendeverjaardag-client
    app.kubernetes.io/component: client
  ports:
    - name: http
      port: 8080
      targetPort: http
