apiVersion: apps/v1
kind: Deployment
metadata:
  name: volgendeverjaardag-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: volgendeverjaardag-server
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: volgendeverjaardag-server
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: server
          image: ghcr.io/wesleyklop/volgendeverjaardag.nl-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
