apiVersion: v1
kind: Service
metadata:
  name: volgendeverjaardag-server
spec:
  selector:
    app.kubernetes.io/name: volgendeverjaardag-server
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8080
      targetPort: http