name: Create build artifacts

on:
  workflow_dispatch: { }
  release:
    types: [published]

jobs:
  release-container:
    name: Build and push image ${{ matrix.app }}
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: true
      matrix:
        include:
          - app: client
            qemu-platform: arm64
            build-platform: linux/amd64
          - app: server
            qemu-platform: arm64
            build-platform: linux/amd64,linux/arm64
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        if: ${{ matrix.qemu-platform }}
        with:
          platforms: ${{ matrix.qemu-platform }} 
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.app }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.build-platform }}
          context: ${{ matrix.app }} 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  update-kustomize:
    name: Update kustomize file
    runs-on: ubuntu-22.04
    needs:
      - release-container
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          flavor: |
            latest=false
          images: |
            ghcr.io/${{ github.repository }}-client
            ghcr.io/${{ github.repository }}-server
          tags: |
            type=semver,pattern={{version}}
      - name: Set image versions in kustomize file
        run: |
          echo '${{ steps.meta.outputs.json }}' | jq -c '.tags[]' | xargs -L 1 kustomize edit set image
        working-directory: manifests
      - uses: EndBug/add-and-commit@v9
        with:
          add: manifests
          default_author: github_actions
          message: Update image versions to ${{ github.ref_name }}
          new_branch: release/${{ github.ref_name }}
          push: true
          tag: ${{ github.ref_name }} --force
          tag_push: --force

