name: Create build artifacts

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
  pull_request:

jobs:
  release-container:
    name: Build and push image ${{ matrix.app }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: true
      matrix:
        app: ['client', 'server']
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v3.6.2
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,enable=true,value=latest
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm64
          context: ${{ matrix.app }} 
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max