name: Manual releases

on:
  workflow_dispatch:
    inputs:
      bump:
        description: How big is the change?
        type: choice
        required: true
        options:
          - major
          - minor
          - patch
      suffix:
        description: Tag suffix
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: version
        with:
          script: |
            const determineNextVersion = await import(
              '${{ github.workspace }}/.github/scripts/version.mjs'
            ).then(m => m.default)
            await determineNextVersion({ context, core, github })
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: ${{ steps.version.outputs.name }}
          tag_name: ${{ steps.version.outputs.tag }} 
          generate_release_notes: true
          draft: true