name: Validation

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-server:
    runs-on: ubuntu-22.04
    name: Lint / server
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.26.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('server/lock.json') }}
      - run: deno cache --reload --lock=lock.json src/deps.ts
        working-directory: server
      - run: deno fmt --check
        working-directory: server
      - run: deno lint
        working-directory: server

  lint-client:
    runs-on: ubuntu-22.04
    name: Lint / client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: client/.nvmrc
          cache: npm
          cache-dependency-path: |
            client/package-lock.json
      - run: npm ci
        working-directory: client
      - run: npm run fmt -- --check
        working-directory: client
